### ISSUE TITLE
Crashes on all Cursed Legacy versions later than 0.9.2:453b245

### ISSUE THREAD

**Issue by gnomed-by-steve** [paulevsGitch/BetterNetherBeta#1]
This is more of an issue with Station API 1.3/1.3.1 being really old, but I think it should still be said somewhere in case others want to play this.
Crash log showcasing this on CL1.0: [paste.ee](https://paste.ee/p/MVIAC)

**Comment by paulevsGitch** [comment]
In my MultiMC instance I used 0.10.6 Loader version and it works fine. Actually yes, this is an old StAPI bug, but BNB is not compatible with newer StAPI build. Probably I will try to update it to 2.0, in this case the problem will be gone, I think

**Comment by paulevsGitch** [comment]
Since the port to new StAPI 2.0 [was started](https://github.com/paulevsGitch/BetterNetherBeta/tree/stapi-2.0) I'm closing this issue. After a month or two new version of BNB with much more polished gameplay and features will be available
